security:
  oauth2:
    resource:
      userInfoUri: http://authenticationservice/auth/user

camunda.bpm:
  database:
    schema-update: false
    type: mariadb
  webapp:
    index-redirect-enabled: true
  admin-user:
    id: camunda
    password: Cooper&camunda
  authorization:
    enabled: true
  filter:
    create: All tasks


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/

signing:
  key: "345345fsdfsf5345"

spring:
  datasource:
    initialization-mode: NEVER
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
    url: "jdbc:mysql://database:3306/camunda?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    database: "MYSQL"
    show-sql: "false"
    hibernate:
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
    properties:
      hibernate:
        ddl-auto: "none"
        enable_lazy_load_no_trans: true
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  cloud:
    stream:
      rocketmq:
        binder:
          name-server:
            rmqnamesrv:9876
      bindings:
        fireCheckBusiness:
          destination: fireCheckBusinessTopic
          content-type: application/json