logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    cc.coopersoft: DEBUG
    org.camunda.bpm.engine.impl.persistence.entity: DEBUG


camunda.bpm:
  database:
    schema-update: true
    type: mysql
  webapp:
    index-redirect-enabled: true
  admin-user:
    id: camunda
    password: Cooper&camunda


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://192.168.1.21:8901/auth/realms/construction/protocol/openid-connect/certs
  cloud:
    stream:
      rocketmq:
        binder:
          name-server:
            192.168.1.21:9876
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/CONSTRUCT?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false"
    username: "root"
    password: "5257mq99"
    platform: mysql
    initialization-mode: always
  jpa:
    show-sql: "true"